### ISSUE TITLE
panic: runtime error: index out of range, when using AD Explorer

### ISSUE THREAD

**Issue by slemire** [Macmod/ldapx#1]
ldapx runs fine with bloodhound-py and ldapsearch but crashes when I connect using AD Explorer

```
goroutine 19 [running]:
main.handleLDAPConnection.func3()
        C:/source/ldapx/proxy.go:139 +0x7aa
created by main.handleLDAPConnection in goroutine 18
        C:/source/ldapx/proxy.go:115 +0x7b6
```

To reproduce:
- Start ldapx without any middleware: `ldapx -t x.x.x.x:389`
- Connect to 127.0.0.1 with AD Explorer

**Comment by slemire** [comment]
Could be because ADExplorer uses GSS-API, based on some pcaps I took

**Comment by Macmod** [comment]
I'll look into this. Thanks for pointing it out!

**Comment by Macmod** [comment]
Apparently some messages sent by AD Explorer during SASL / GSSAPI establishment don't fit the "standard" expected format for LDAP messages. I'll try to check in the following days if we can just detect this condition somehow and get it working by just sending these "extra" packets back and forward between client and server.

**Comment by Macmod** [comment]
Seems liks this is a bigger issue than I first thought - even if we could make it not panic and forward the messages back and forth, SASL/GSS-API encrypts the messages, so ldapx would not actually do anything but sit in the middle of the connection. So we can either:
(1) Explicitly state that ldapx doesn't support SASL / GSSAPI (not ideal)
(2) Add a flag to try to "downgrade" the auth somehow by intercepting the first BindResponse (theoretically possible?)
(3) Implement active decryption of SASL / GSSAPI in ldapx (theoretically possible, but harder)

I'll have to study which of (2) and (3) is the way out, but more testing is definitely needed to solve this one.

**Comment by RedHeadSec** [comment]
I've confirmed a similar issue with [Ldeep](https://github.com/franc-pentest/ldeep) that may be related. Unless encryption is disabled on the tool side, it runs into an fatal error below (ldeep): 

```
  File "/opt/ldeep/lib/python3.12/site-packages/ldap3/strategy/sync.py", line 137, in receiving
    sasl_received_data = self.connection.ntlm_client.unseal(sasl_received_data[:sasl_buffer_length])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/ldeep/lib/python3.12/site-packages/ldap3/utils/ntlm.py", line 560, in unseal
    raise LDAPSignatureVerificationFailedError("Signature verification failed for the received LDAP message number " + str(self.sequence_number) + ". Expected signature " + sealed_message[:16].hex() + " but got " + calculated_signature.hex() + ".")
ldap3.core.exceptions.LDAPSignatureVerificationFailedError: Signature verification failed for the received LDAP message number 1. Expected signature  but got 0100000088ae3b86a6af14cd.
```
Ldapx Error:
```
panic: runtime error: index out of range [1] with length 0

goroutine 20 [running]:
main.handleLDAPConnection.func3()
	/opt/ldapx/proxy.go:161 +0x7a5
created by main.handleLDAPConnection in goroutine 19
	/opt/ldapx/proxy.go:137 +0x776
```
![image](https://github.com/user-attachments/assets/7d221c97-db43-4878-8cb7-addc78823cfb)

![image](https://github.com/user-attachments/assets/53cb0680-a3a8-4656-9f9d-6c163871b841)

Disabling it allows the tool to function correctly.

**Comment by LeeDuncan77new** [comment]
> **[16/12/2024] Update**. I tried to intercept the BindResponse and reply an `authMethodNotSupported` (resultCode 7) to ADExplorer - it seems that it first tries to use `SASL / GSSAPI` (type 3), and if it gets an `authMethodNotSupported` back it tries again with `NTLMSSP Negotiate` (type 10). But then, if we reply code 7 again, it just sends an `UnbindRequest` and throws an alert saying that the server does not support the requested authentication method.

Could you let me know how you did that?  I am attempting to use ldapx to proxy a closed source client.  It appears to give up after being told ntml isn't available and try simple, but I'm not able to test because I can't make that happen reliably.  Currently ldapx quits and dumps that index error message.

**Comment by LeeDuncan77new** [comment]
> > **[16/12/2024] Update**. I tried to intercept the BindResponse and reply an `authMethodNotSupported` (resultCode 7) to ADExplorer - it seems that it first tries to use `SASL / GSSAPI` (type 3), and if it gets an `authMethodNotSupported` back it tries again with `NTLMSSP Negotiate` (type 10). But then, if we reply code 7 again, it just sends an `UnbindRequest` and throws an alert saying that the server does not support the requested authentication method.
> 
> Could you let me know how you did that? I am attempting to use ldapx to proxy a closed source client. It appears to give up after being told ntml isn't available and try simple, but I'm not able to test because I can't make that happen reliably. Currently ldapx quits and dumps that index error message.

And after reading some more what I'm seeing is different then this.  Sorry to pollute this issue.
